### ISSUE TITLE
The title of each test should clearly state what should be done

### ISSUE THREAD

**Issue by JazJas** [dev-sec/windows-baseline#18]
This is not a bug, rather a comment. The title of each test should clearly state what should be done or what should not be done. 
For instance:
 'windows-base-105'
  title 'SMB1 to Windows Shares is disabled' 
It would be better to update the title to something like:
  title 'SMB1 to Windows Shares should be disabled' 

'windows-base-203'
  title 'Enable Strong Encryption for Windows Network Sessions on Servers'
It would be better to update the title to something like:
  title 'Strong Encryption for Windows Network Sessions on Servers should be enabled'

Thanks.

**Comment by atomic111** [comment]
@JazJas I developed a new baseine. please have a look. now it should be clear, hopefully

Can i close the issue?

**Comment by JazJas** [comment]
Looks great! Much clearer! Thanks for your update. Close this issue.
