### ISSUE TITLE
Should we close SeNetworkLogonRight for all users?

### ISSUE THREAD

**Issue by strangeman** [dev-sec/windows-baseline#19]
Reference https://github.com/dev-sec/ansible-windows-hardening/pull/3

I think we should allow NetworkLogon for Administrator group, because instead we cannot manage Windows Server via WinRM:
https://github.com/dev-sec/windows-baseline/blob/master/controls/user_rights.rb#L19
```diff
+    its('SeNetworkLogonRight') { should eq ['S-1-5-32-544'] }
-    its('SeNetworkLogonRight') { should eq ['S-1-0-0'] }
```

**Comment by chris-rock** [comment]
I think we should have the capability to use the baseline with winrm and without winrm. There are good reasons to deactivate winrm on secure production environments. Therefore we need to distinguish between two options:

- deactivate winrm
- best-practices for winrm (which accounts, https only, certs)

@strangeman would that suite your needs?

**Comment by chris-rock** [comment]
@atomic111 what are you thinking?

**Comment by strangeman** [comment]
@chris-rock yeah, options for well-secured WinRM would be useful.

**Comment by jborean93** [comment]
If anything, you need to change the Ansible role to allow it like https://github.com/dev-sec/ansible-windows-hardening/pull/3. When setting it to nobody you stop the mechanism that Ansible uses to connect to the host.

**Comment by atomic111** [comment]
@strangeman and @jborean93 I introduced a new inspec attribute for this https://github.com/dev-sec/windows-baseline/blob/master/inspec.yml#L33

Can i close the issue?

**Comment by strangeman** [comment]
Yeah, looks good for me.
