### ISSUE TITLE
formatting error when executing profile

### ISSUE THREAD

**Issue by vjeffrey** [dev-sec/windows-baseline#34]
**Describe the bug**
In some recent testing I discovered this profile is failing inspec exec with some formatting issues.

**Expected behavior**
Can execute this profile with inspec exec and send the results to Automate

**Actual behavior**

```
         2: from C:/opscode/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/reporters/automate.rb:41:in
 `send_report'
         1: from C:/opscode/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/reporters/automate.rb:41:in
 `to_json'
C:/opscode/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/reporters/automate.rb:41:in `encode': "\xC3"
 from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
```

**OS / Environment**
windows_server_2016

**Inspec Version**
inspec 3.9.0

**Baseline Version**
master

**Additional context**
 https://github.com/chef/automate/issues/296

**Comment by atomic111** [comment]
@vjeffrey thank you for identifing it. Sorry my fault. can you do me a fever and use the following grep command to identify the points. I noticed also i have some german texts in the description section. Can you please also add the CIS english texts to this and open a merge request with the changes?

```
grep --color='auto' -P -n '[^\x00-\x7F]' administrative_templates_computer.rb                                                                                                      x1 21d master[f4f7534]
3111:  desc 'Diese Richtlinieneinstellung gibt die maximale Größe der Protokolldatei in Kilobyte an. Die maximale Protokolldateigröße kann zwischen 1 Megabyte (1.024 Kilobyte) und 2 Terabyte (2.147.483.647 Kilobyte) in Kilobyte-Schritten konfiguriert werden.
3113:  Der empfohlene Status für diese Einstellung ist: Enabled: 32,768 or greater.
```

that would be great to support the dev-sec project

Thanks

**Comment by vjeffrey** [comment]
yes, thank you for the grep command! i will try to get to this work (either myself or someone on my team) in the next week or so). thank you!

**Comment by alexpop** [comment]
Hey Patrick. Thanks for the reply. 
Majority of the problematic characters are coming from the German description and tags. If I understand correctly, do you want those to be replaced with English ones?
