### ISSUE TITLE
Typo FontBocking/FontBlocking?

### ISSUE THREAD

**Issue by rndmh3ro** [dev-sec/windows-baseline#35]
**Describe the bug**
In control windows-249 there is a mitigation called `MitigationOptions_FontBocking` instead of `MitigationOptions_FontBlocking`

I don't know if this is correct.
Stig viewer has the same typo: https://www.stigviewer.com/stig/windows_10/2015-11-30/finding/V-63641

For Windows 10 Font Blocking works entirely different: https://docs.microsoft.com/en-us/windows/security/threat-protection/block-untrusted-fonts-in-enterprise

```
  describe registry_key('HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\MitigationOptions') do
    it { should exist }
    it { should have_property 'MitigationOptions_FontBocking' }
    its('MitigationOptions_FontBocking') { should eq '1000000000000' }
end
```

We should check what option actually blocks untrusted fonts.

**Comment by atomic111** [comment]
@rndmh3ro i just found stuff with the typo and the windows 10 stuff. For now, it seems to be that the Windows 10 implementation is correct. But need a further investigation

**Comment by imjoseangel** [comment]
The right key is `MitigationOptions_FontBocking`. I think there is no issue here.

**Comment by imjoseangel** [comment]
Hi I think this should be closed as there is no Typo. What do you think?

**Comment by rndmh3ro** [comment]
I agree.
