### ISSUE TITLE
Licensing information mismatch?

### ISSUE THREAD

**Issue by techraf** [dev-sec/windows-baseline#4]
Controls in this repo (numbers 04-08) contain the following information in the headers:

```
# copyright: 2015, Chef Software, Inc
# license: All rights reserved
```

Pardon my ignorance, but isn't it contradictory to the general Apache License specified at the repo level?

**Comment by artem-sidorenko** [comment]
@chris-rock ping:)

**Comment by chris-rock** [comment]
@techraf Yes, this was open sourced by Chef. As indicated in https://github.com/dev-sec/windows-baseline/blob/master/LICENSE, the whole implementation is Apache 2 licensed. I'll adapt this

**Comment by chris-rock** [comment]
Thank you for highlighting this issue @techraf
