### ISSUE TITLE
False Positives due to integers in strings

### ISSUE THREAD

**Issue by kjake** [dev-sec/windows-baseline#45]
**Describe the bug**
Many Inspec tests are failing the test when Windows stores a numerical value as a string.

**Expected behavior**
Tests should pass when the expected value is either a number or string

**Actual behavior**
```
AllocateDASD
is expected to eq 
  Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

    expected: 0
         got: "0"

    (compared using ==)
  # windows-baseline-master/controls/local_policies.rb:1094:in `block (3 levels) in load_with_context'
```

**OS / Environment**
Domain-joined Windows Server 2016/2019

**Inspec Version**
```
4.20.10
```

**Baseline Version**
```
2.1.4
```

**Additional context**

I believe the recommendation from Opscode is to use `cmp` instead of `eq`

**Comment by imjoseangel** [comment]
Hi @kjake Do you have the list of tests failing?

**Comment by kjake** [comment]
Hi! I tested the PR and it did seem to work for those two cases that you fixed.  I documented all of the similar issues that I noticed this time. As follows...

In administrative_templates_computer.rb the following controls are outputting things like:
```
expected: 1
     got: "1"
```
Controls:
- windows-289
- windows-291
- windows-293
- windows-295
- windows-331

In administrative_templates_computer.rb windows-200 output:
```
expected: <= 5
     got:    "5"
```

in local_policies.rb control windows-091 output:
```
expected: []
     got: [""]
```

**Comment by imjoseangel** [comment]
Thank you @kjake . I didn't catch those. I will re-test carefully and get back with the amends.

**Comment by imjoseangel** [comment]
Hi @kjake ,

After testing and taking into account your comments I got this:

```
windows-289
windows-291
windows-293
windows-295
windows-331
```
**Changed**

Regarding Windows-200. It must be a REG_DWORD value. If the output is "5", the configuration is wrong and configured as `REG_SZ` and not as `REG_DWORD`. Check [This](https://getadmx.com/?Category=SecurityBaseline&Policy=Microsoft.Policies.MSS::Pol_MSS_ScreenSaverGracePeriod)

Same for the windows-091 I'm getting this and will analyze why you could get [""]

```
     ✔  Registry Key HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters NullSessionPipes is expected to eq []
```

**Comment by kjake** [comment]
Regarding Windows-200, I am using the "Microsoft Security Compliance Toolkit" from https://www.microsoft.com/en-us/download/details.aspx?id=55319 to set these, so Microsoft is setting a REG_SZ.  Likewise, the STIG recommendation, as of Windows 8, was to use REG_SZ: https://www.stigviewer.com/stig/windows_8_8.1/2014-04-02/finding/V-4442

Regarding windows-091, my value is "empty", but when I open it in the registry editor, it appears there is a newline in there (REG_MULTI_SZ type). I re-did the policy setting, and made sure there were no spaces or new lines / carriage returns in the GP editor. Refreshed the GP, and the Registry and that "new line" is still there. I'm using the standard Group Policy editor and settings on a Windows 2019 server to do my work and testing.

**Comment by imjoseangel** [comment]
Hi @kjake Thank you so much for your comments. I test both taking into account your scenario and mine to be as much compatible as possible.

**Comment by imjoseangel** [comment]
@kjake Could you please review? I have tested both scenarios in windows-091.

Thank you!

**Comment by kjake** [comment]
This now looks great!  I may dig into some other failures to validate, but for the purposes of this issue, I would consider it solved!  Thank so much 👍 

Will you merge when this closes?

**Comment by imjoseangel** [comment]
With your confirmation the team will approve the PR and the issue will close automatically.

Thank you!

**Comment by imjoseangel** [comment]
Hey @kjake keep the issue opened until merged. That should be the right process.

Thank you!!!
